apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openldap-ingress
  namespace: identity
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openldap
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: identity
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: slurm
      ports:
        - protocol: TCP
          port: 389
