apiVersion: v1
kind: Secret
metadata:
  name: openldap-credentials
  namespace: identity
type: Opaque
stringData:
  adminPassword: adminpassword
  configPassword: configpassword
  readerPassword: readerpassword
