apiVersion: v1
kind: Secret
metadata:
  name: site-sssd-ha-ldap-conf
  namespace: slurm
type: Opaque
stringData:
  sssd.conf: |
    [sssd]
    config_file_version = 2
    services = nss,pam,ssh
    domains = LDAP

    [nss]
    filter_users = root,slurm
    filter_groups = root,slurm
    entry_cache_timeout = 60
    entry_cache_nowait_percentage = 75

    [pam]

    [ssh]

    [domain/LDAP]
    id_provider = ldap
    auth_provider = ldap
    access_provider = permit

    ldap_uri = ldap://openldap-0.openldap-headless.identity.svc.cluster.local:389,ldap://openldap-1.openldap-headless.identity.svc.cluster.local:389,ldap://openldap-2.openldap-headless.identity.svc.cluster.local:389
    ldap_search_base = dc=example,dc=org
    ldap_user_search_base = ou=People,dc=example,dc=org
    ldap_group_search_base = ou=Groups,dc=example,dc=org

    ldap_schema = rfc2307
    ldap_id_use_start_tls = false
    ldap_id_mapping = false
    ldap_default_bind_dn = cn=sssd-reader,ou=ServiceAccounts,dc=example,dc=org
    ldap_default_authtok_type = password
    ldap_default_authtok = readerpassword

    ldap_user_object_class = posixAccount
    ldap_user_name = uid
    ldap_user_uid_number = uidNumber
    ldap_user_gid_number = gidNumber
    ldap_user_home_directory = homeDirectory
    ldap_user_shell = loginShell
    ldap_user_ssh_public_key = sshPublicKey

    ldap_group_object_class = posixGroup
    ldap_group_name = cn
    ldap_group_gid_number = gidNumber
    ldap_group_member = memberUid

    cache_credentials = true
    enumerate = false
